/* SYNAPSE i18n — English, French, Russian, Chinese. Shared by 2D and 3D. */
(function () {
  window.SYN_LINKEDIN = 'https://www.linkedin.com/in/jonathan-lamarca/'
  const I18N = {
    en: { view: 'View', intel: 'Intelligence', more: 'More', g2d: '2D graph', g3d: '3D brain', ask: 'Ask JARVIS', capture: 'Quick Capture', today: "Today's Focus", gaps: 'Brain Gaps', voice: 'Voice', vision: 'See screen', call: 'Call JARVIS', exportp: 'Export PNG', commands: 'Commands ⌘K', fit: 'Fit view', rescan: 'Rescan', tune: 'Tune JARVIS', search: 'Search your brain…', online: 'ONLINE', notes: 'Notes', links: 'Links', system: 'System', jsub: 'answers from your notes', jhint: 'Ask anything about your brain. Try "what do we sell?" or hit Brain Gaps.', jph: 'Ask, or tap the mic…', askbtn: 'Ask', linksout: 'Links out', backlinks: 'Backlinks', none: 'none', endcall: 'End call', st_listen: 'Listening', st_think: 'Thinking', st_speak: 'Speaking', cap_title: 'Capture a thought', cap_desc: 'Type or speak anything. JARVIS files it in the right place, tags it and links it.', cap_btn: 'Capture', wtitle: 'Your notes, alive.', wp: 'SYNAPSE turns a folder of notes into a living brain.', wb1: 'Click a node to read the note and everything it connects to.', wb2: 'Ask JARVIS, or call it, to get answers from your own notes.', wb3: 'Brain Gaps shows you links your notes are missing.', wb4: 'Press Cmd K for commands and to jump to any note.', wexplore: 'Explore my brain', wtour: 'Take the tour', credit: 'Created by Jonathan Lamarca', lic_title: 'Activate SYNAPSE', lic_desc: 'Enter your license key to unlock your brain.', lic_activate: 'Activate', lic_get: 'No key? DM Jonathan Lamarca on Skool to get one.', lic_invalid: 'Invalid key. DM Jonathan on Skool for a valid one.' },
    fr: { view: 'Vue', intel: 'Intelligence', more: 'Plus', g2d: 'Graphe 2D', g3d: 'Cerveau 3D', ask: 'Demander à JARVIS', capture: 'Capture rapide', today: 'Focus du jour', gaps: 'Liens manquants', voice: 'Voix', vision: "Voir l'écran", call: 'Appeler JARVIS', exportp: 'Exporter PNG', commands: 'Commandes ⌘K', fit: 'Ajuster', rescan: 'Rescanner', tune: 'Régler JARVIS', search: 'Cherchez dans votre cerveau…', online: 'EN LIGNE', notes: 'Notes', links: 'Liens', system: 'Système', jsub: 'répond depuis vos notes', jhint: 'Demandez tout sur votre cerveau. Essayez "qu\'est-ce qu\'on vend ?" ou lancez Brain Gaps.', jph: 'Demandez, ou touchez le micro…', askbtn: 'Envoyer', linksout: 'Liens sortants', backlinks: 'Rétroliens', none: 'aucun', endcall: 'Raccrocher', st_listen: 'Écoute', st_think: 'Réflexion', st_speak: 'Parle', cap_title: 'Capturez une pensée', cap_desc: 'Écrivez ou dictez n\'importe quoi. JARVIS la range au bon endroit, la tague et la relie.', cap_btn: 'Capturer', wtitle: 'Vos notes, vivantes.', wp: 'SYNAPSE transforme un dossier de notes en cerveau vivant.', wb1: 'Cliquez un nœud pour lire la note et tout ce à quoi elle est reliée.', wb2: 'Demandez à JARVIS, ou appelez-le, pour des réponses tirées de vos notes.', wb3: 'Brain Gaps vous montre les liens qui manquent à vos notes.', wb4: 'Appuyez Cmd K pour les commandes et sauter à n\'importe quelle note.', wexplore: 'Explorer mon cerveau', wtour: 'Faire le tour', credit: 'Créé par Jonathan Lamarca', lic_title: 'Activer SYNAPSE', lic_desc: 'Entrez votre clé de licence pour débloquer votre cerveau.', lic_activate: 'Activer', lic_get: 'Pas de clé ? Envoyez un DM à Jonathan Lamarca sur Skool pour en obtenir une.', lic_invalid: 'Clé invalide. DM à Jonathan sur Skool pour une clé valide.' },
    ru: { view: 'Вид', intel: 'Интеллект', more: 'Ещё', g2d: '2D граф', g3d: '3D мозг', ask: 'Спросить JARVIS', capture: 'Быстрая запись', today: 'Фокус дня', gaps: 'Пробелы связей', voice: 'Голос', vision: 'Смотреть экран', call: 'Позвонить JARVIS', exportp: 'Экспорт PNG', commands: 'Команды ⌘K', fit: 'Вписать', rescan: 'Пересканировать', tune: 'Настроить JARVIS', search: 'Ищите в вашем мозге…', online: 'ОНЛАЙН', notes: 'Заметки', links: 'Связи', system: 'Система', jsub: 'отвечает по вашим заметкам', jhint: 'Спросите что угодно о вашем мозге. Попробуйте "что мы продаём?" или Brain Gaps.', jph: 'Спросите или нажмите микрофон…', askbtn: 'Спросить', linksout: 'Исходящие', backlinks: 'Обратные ссылки', none: 'нет', endcall: 'Завершить', st_listen: 'Слушаю', st_think: 'Думаю', st_speak: 'Говорю', cap_title: 'Запишите мысль', cap_desc: 'Напишите или продиктуйте что угодно. JARVIS сохранит, пометит и свяжет это.', cap_btn: 'Записать', wtitle: 'Ваши заметки оживают.', wp: 'SYNAPSE превращает папку заметок в живой мозг.', wb1: 'Нажмите на узел, чтобы прочитать заметку и все её связи.', wb2: 'Спросите JARVIS или позвоните ему, чтобы получить ответы из ваших заметок.', wb3: 'Brain Gaps показывает недостающие связи ваших заметок.', wb4: 'Нажмите Cmd K для команд и перехода к любой заметке.', wexplore: 'Исследовать мой мозг', wtour: 'Пройти тур', credit: 'Создано Jonathan Lamarca', lic_title: 'Активировать SYNAPSE', lic_desc: 'Введите лицензионный ключ, чтобы открыть ваш мозг.', lic_activate: 'Активировать', lic_get: 'Нет ключа? Напишите Jonathan Lamarca в Skool, чтобы получить его.', lic_invalid: 'Неверный ключ. Напишите Jonathan в Skool.' },
    zh: { view: '视图', intel: '智能', more: '更多', g2d: '2D 图谱', g3d: '3D 大脑', ask: '问 JARVIS', capture: '快速记录', today: '今日重点', gaps: '大脑缺口', voice: '语音', vision: '查看屏幕', call: '呼叫 JARVIS', exportp: '导出 PNG', commands: '命令 ⌘K', fit: '适配视图', rescan: '重新扫描', tune: '调整 JARVIS', search: '搜索你的大脑…', online: '在线', notes: '笔记', links: '链接', system: '系统', jsub: '从你的笔记回答', jhint: '问关于你大脑的任何问题。试试"我们卖什么？"或点 Brain Gaps。', jph: '提问，或点击麦克风…', askbtn: '提问', linksout: '出链', backlinks: '反向链接', none: '无', endcall: '结束通话', st_listen: '聆听中', st_think: '思考中', st_speak: '说话中', cap_title: '记录一个想法', cap_desc: '打字或说话。JARVIS 会归档、加标签并建立链接。', cap_btn: '记录', wtitle: '你的笔记，活起来了。', wp: 'SYNAPSE 把一个笔记文件夹变成一个活的大脑。', wb1: '点击一个节点，阅读笔记及其所有连接。', wb2: '问 JARVIS 或呼叫它，直接从你的笔记获得答案。', wb3: 'Brain Gaps 显示你笔记缺失的链接。', wb4: '按 Cmd K 打开命令并即时跳到任意笔记。', wexplore: '探索我的大脑', wtour: '开始导览', credit: '由 Jonathan Lamarca 创建', lic_title: '激活 SYNAPSE', lic_desc: '输入你的许可证密钥以解锁你的大脑。', lic_activate: '激活', lic_get: '没有密钥？在 Skool 私信 Jonathan Lamarca 获取。', lic_invalid: '密钥无效。在 Skool 私信 Jonathan。' },
  }
  let LANG = 'en'; try { LANG = localStorage.getItem('synapse_lang') || (navigator.language || 'en').slice(0, 2) } catch (e) { }
  if (!I18N[LANG]) LANG = 'en'
  window.SYN_LANG = function () { return LANG }
  window.SYN_T = function (k) { return (I18N[LANG] && I18N[LANG][k]) || I18N.en[k] || k }
  window.SYN_applyLang = function () {
    document.querySelectorAll('[data-t]').forEach(function (e) { e.textContent = window.SYN_T(e.dataset.t) })
    document.querySelectorAll('[data-tp]').forEach(function (e) { e.placeholder = window.SYN_T(e.dataset.tp) })
    document.documentElement.lang = LANG
    document.querySelectorAll('.langopt').forEach(function (o) { o.classList.toggle('on', o.dataset.lang === LANG) })
  }
  window.SYN_setLang = function (l) { if (!I18N[l]) return; LANG = l; try { localStorage.setItem('synapse_lang', l) } catch (e) { } window.SYN_applyLang() }
})()
