const { chromium } = require('/opt/lamarca-web-studio/node_modules/playwright')
const fs = require('fs')
const LOG = '/tmp/claude-0/-root--openclaw-workspace/6b327273-6640-43e8-9cd2-01cc39ea3000/scratchpad/create.log'
const log = (...a) => { fs.appendFileSync(LOG, '> ' + a.join(' ') + '\n') }
fs.writeFileSync(LOG, 'start ' + new Date().toISOString() + '\n')

;(async () => {
  const b = await chromium.connectOverCDP('http://127.0.0.1:9224', { timeout: 15000 })
  log('connected')
  const ctx = b.contexts()[0]
  const p = await ctx.newPage()
  await p.setViewportSize({ width: 1440, height: 900 })
  await p.goto('https://www.skool.com/house-of-lamarca-/classroom', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(e => log('nav', e.message))
  await p.waitForTimeout(4000); log('classroom loaded')
  await p.evaluate(() => { const el = [...document.querySelectorAll('*')].find(e => e.children.length <= 2 && (e.textContent || '').trim() === 'New course'); if (el) el.click() })
  await p.getByText('Add course').waitFor({ timeout: 8000 }).catch(async () => { log('retry New course click'); await p.evaluate(() => { const el = [...document.querySelectorAll('*')].find(e => e.children.length <= 2 && (e.textContent || '').trim() === 'New course'); if (el) el.click() }); await p.getByText('Add course').waitFor({ timeout: 8000 }) })
  log('modal open')
  const dlg = p.locator('div').filter({ hasText: /Add course/ }).last()
  await p.getByLabel('Course name').fill('Build Your JARVIS'); log('name filled')
  await p.getByLabel('Course description').fill('Turn your notes into a JARVIS that knows you. Install it, make it answer from your own notes by text or voice, make it adapt to you, then sell it. Five modules, seventeen lessons.'); log('desc filled')
  await p.setInputFiles('input[type=file]', '/opt/synapse/course/jarvis-cover.png'); log('file set')
  const saveBtn = p.getByRole('button', { name: 'Save' })
  await saveBtn.waitFor({ timeout: 12000 }); log('crop Save visible')
  await saveBtn.click({ timeout: 8000 }); log('crop saved')
  await p.waitForTimeout(2500)
  const nameVal = await p.getByPlaceholder('Course name').inputValue().catch(() => '?'); log('name field now =', JSON.stringify(nameVal))
  const addBtn = p.getByRole('button', { name: 'Add', exact: true })
  await addBtn.waitFor({ timeout: 8000 }); log('Add visible')
  await addBtn.click({ timeout: 8000 }); log('clicked Add')
  await p.waitForTimeout(5000)
  await p.screenshot({ path: '/opt/synapse/course/created.png' })
  const has = await p.evaluate(() => [...document.querySelectorAll('*')].some(e => e.children.length === 0 && e.textContent.trim() === 'Build Your JARVIS'))
  log('course present:', has, 'url:', p.url())
  log('DONE')
  await b.close()
})().catch(e => log('ERR', e.message, e.stack ? e.stack.split('\n')[1] : ''))
