const { chromium } = require('/opt/lamarca-web-studio/node_modules/playwright')
const fs = require('fs')
const LOG = '/tmp/claude-0/-root--openclaw-workspace/6b327273-6640-43e8-9cd2-01cc39ea3000/scratchpad/menu.log'
const log = (...a) => fs.appendFileSync(LOG, a.join(' ') + '\n')
fs.writeFileSync(LOG, 'menu ' + new Date().toISOString() + '\n')
;(async () => {
  const b = await chromium.connectOverCDP('http://127.0.0.1:9224', { timeout: 15000 })
  const ctx = b.contexts()[0]
  const p = await ctx.newPage()
  await p.setViewportSize({ width: 1440, height: 900 })
  await p.goto('https://www.skool.com/house-of-lamarca-/classroom/3f8ae1e9', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(e => log('nav', e.message))
  await p.waitForTimeout(4000)
  // click course-level "..." at ~ (481,158)
  await p.mouse.click(481, 158); await p.waitForTimeout(1200)
  let items = await p.evaluate(() => [...document.querySelectorAll('[role=menuitem],li,button')].map(e => e.textContent.trim()).filter(t => t && t.length < 30))
  log('COURSE MENU:', JSON.stringify([...new Set(items)]))
  await p.screenshot({ path: '/opt/synapse/course/course_menu.png' })
  await p.keyboard.press('Escape'); await p.waitForTimeout(500)
  // hover the New page row, then click its "..." at ~ (481,250)
  await p.mouse.move(336, 250); await p.waitForTimeout(400)
  await p.mouse.click(481, 250); await p.waitForTimeout(1200)
  items = await p.evaluate(() => [...document.querySelectorAll('[role=menuitem],li,button')].map(e => e.textContent.trim()).filter(t => t && t.length < 30))
  log('PAGE MENU:', JSON.stringify([...new Set(items)]))
  await p.screenshot({ path: '/opt/synapse/course/page_menu.png' })
  log('DONE')
  await b.close()
})().catch(e => log('ERR', e.message))
