const { chromium } = require('/opt/lamarca-web-studio/node_modules/playwright')
const fs=require('fs'); const LOG='/tmp/claude-0/-root--openclaw-workspace/6b327273-6640-43e8-9cd2-01cc39ea3000/scratchpad/tfm.log'
const log=(...a)=>fs.appendFileSync(LOG,a.join(' ')+'\n'); fs.writeFileSync(LOG,'tfm\n')
;(async()=>{const b=await chromium.connectOverCDP('http://127.0.0.1:9224',{timeout:15000});const ctx=b.contexts()[0];const p=await ctx.newPage()
await p.setViewportSize({width:1440,height:900})
await p.goto('https://www.skool.com/house-of-lamarca-/classroom/3f8ae1e9',{waitUntil:'domcontentloaded',timeout:30000}).catch(e=>log('nav',e.message))
await p.waitForTimeout(4000)
const y=await p.evaluate(()=>{const t=[...document.querySelectorAll('*')].find(e=>e.children.length===0&&e.textContent.trim()==='Start Here');return t.getBoundingClientRect().y+t.getBoundingClientRect().height/2})
await p.mouse.move(336,y); await p.waitForTimeout(800)
await p.mouse.click(440,y); await p.waitForTimeout(1000)
const items=await p.evaluate(()=>[...document.querySelectorAll('[role=menuitem],li,button,div')].map(e=>e.textContent.trim()).filter(t=>t&&t.length<20&&/add page|add folder|rename|delete|edit/i.test(t)))
log('folder menu:',JSON.stringify([...new Set(items)]))
await p.screenshot({path:'/opt/synapse/course/fmenu2.png'})
log('DONE'); await b.close()})().catch(e=>log('ERR',e.message))
